# Generated by Django 3.0.4 on 2020-03-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('Last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('iin', models.IntegerField(verbose_name='ИИН')),
                ('Phone', models.IntegerField(verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='CreditStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('ACTIVE', 'active'), ('PAID', 'paid')], max_length=150, verbose_name='статус')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='credit.Person')),
            ],
        ),
    ]
