# Generated by Django 3.0.4 on 2020-03-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('iin', models.CharField(max_length=12, verbose_name='ИИН')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('ACTIVE', 'active'), ('PAID', 'paid')], max_length=150, verbose_name='статус')),
                ('cash', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Денги')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.Person')),
            ],
        ),
    ]
