# Generated by Django 3.0.4 on 2020-03-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Phone',
            field=models.IntegerField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='person',
            name='iin',
            field=models.IntegerField(max_length=12, verbose_name='ИИН'),
        ),
    ]
